using LinqAn.Google.Metrics;
using LinqAn.Google.Dimensions;

namespace LinqAn.Google.Records
{
	public interface IQueryableRecord
	{
		uint ViewId { get; }
		System.DateTime RecordDate { get; }
		Users Users { get; }
		NewUsers NewUsers { get; }
		OnedayUsers OnedayUsers { get; }
		SevendayUsers SevendayUsers { get; }
		FourteendayUsers FourteendayUsers { get; }
		ThirtydayUsers ThirtydayUsers { get; }
		Sessions Sessions { get; }
		Bounces Bounces { get; }
		SessionDuration SessionDuration { get; }
		OrganicSearches OrganicSearches { get; }
		Impressions Impressions { get; }
		AdClicks AdClicks { get; }
		AdCost AdCost { get; }
		GoalStartsAll GoalStartsAll { get; }
		GoalCompletionsAll GoalCompletionsAll { get; }
		GoalValueAll GoalValueAll { get; }
		SocialActivities SocialActivities { get; }
		PageValue PageValue { get; }
		Entrances Entrances { get; }
		Pageviews Pageviews { get; }
		UniquePageviews UniquePageviews { get; }
		TimeOnPage TimeOnPage { get; }
		Exits Exits { get; }
		SearchResultViews SearchResultViews { get; }
		SearchUniques SearchUniques { get; }
		SearchSessions SearchSessions { get; }
		SearchDepth SearchDepth { get; }
		SearchRefinements SearchRefinements { get; }
		SearchDuration SearchDuration { get; }
		SearchExits SearchExits { get; }
		PageLoadTime PageLoadTime { get; }
		PageLoadSample PageLoadSample { get; }
		DomainLookupTime DomainLookupTime { get; }
		PageDownloadTime PageDownloadTime { get; }
		RedirectionTime RedirectionTime { get; }
		ServerConnectionTime ServerConnectionTime { get; }
		ServerResponseTime ServerResponseTime { get; }
		SpeedMetricsSample SpeedMetricsSample { get; }
		DomInteractiveTime DomInteractiveTime { get; }
		DomContentLoadedTime DomContentLoadedTime { get; }
		DomLatencyMetricsSample DomLatencyMetricsSample { get; }
		Screenviews Screenviews { get; }
		UniqueScreenviews UniqueScreenviews { get; }
		TimeOnScreen TimeOnScreen { get; }
		AvgScreenviewDuration AvgScreenviewDuration { get; }
		TotalEvents TotalEvents { get; }
		UniqueEvents UniqueEvents { get; }
		EventValue EventValue { get; }
		SessionsWithEvent SessionsWithEvent { get; }
		Transactions Transactions { get; }
		TransactionRevenue TransactionRevenue { get; }
		TransactionShipping TransactionShipping { get; }
		TransactionTax TransactionTax { get; }
		ItemQuantity ItemQuantity { get; }
		UniquePurchases UniquePurchases { get; }
		ItemRevenue ItemRevenue { get; }
		LocalTransactionRevenue LocalTransactionRevenue { get; }
		LocalTransactionShipping LocalTransactionShipping { get; }
		LocalTransactionTax LocalTransactionTax { get; }
		LocalItemRevenue LocalItemRevenue { get; }
		SocialInteractions SocialInteractions { get; }
		UniqueSocialInteractions UniqueSocialInteractions { get; }
		UserTimingValue UserTimingValue { get; }
		UserTimingSample UserTimingSample { get; }
		Exceptions Exceptions { get; }
		FatalExceptions FatalExceptions { get; }
		DcmFloodlightQuantity DcmFloodlightQuantity { get; }
		DcmFloodlightRevenue DcmFloodlightRevenue { get; }
		AdsenseRevenue AdsenseRevenue { get; }
		AdsenseAdUnitsViewed AdsenseAdUnitsViewed { get; }
		AdsenseAdsViewed AdsenseAdsViewed { get; }
		AdsenseAdsClicks AdsenseAdsClicks { get; }
		AdsensePageImpressions AdsensePageImpressions { get; }
		AdsenseExits AdsenseExits { get; }
		AdsenseViewableImpressionPercent AdsenseViewableImpressionPercent { get; }
		AdsenseCoverage AdsenseCoverage { get; }
		AdxImpressions AdxImpressions { get; }
		AdxCoverage AdxCoverage { get; }
		AdxMonetizedPageviews AdxMonetizedPageviews { get; }
		AdxImpressionsPerSession AdxImpressionsPerSession { get; }
		AdxViewableImpressionsPercent AdxViewableImpressionsPercent { get; }
		AdxClicks AdxClicks { get; }
		AdxCTR AdxCTR { get; }
		AdxRevenue AdxRevenue { get; }
		AdxRevenuePer1000Sessions AdxRevenuePer1000Sessions { get; }
		AdxECPM AdxECPM { get; }
		BuyToDetailRate BuyToDetailRate { get; }
		CartToDetailRate CartToDetailRate { get; }
		CorrelationScore CorrelationScore { get; }
		DcmCPC DcmCPC { get; }
		DcmCTR DcmCTR { get; }
		DcmClicks DcmClicks { get; }
		DcmCost DcmCost { get; }
		DcmImpressions DcmImpressions { get; }
		DcmROAS DcmROAS { get; }
		DcmRPC DcmRPC { get; }
		Hits Hits { get; }
		InternalPromotionClicks InternalPromotionClicks { get; }
		InternalPromotionViews InternalPromotionViews { get; }
		LocalProductRefundAmount LocalProductRefundAmount { get; }
		LocalRefundAmount LocalRefundAmount { get; }
		ProductAddsToCart ProductAddsToCart { get; }
		ProductCheckouts ProductCheckouts { get; }
		ProductDetailViews ProductDetailViews { get; }
		ProductListClicks ProductListClicks { get; }
		ProductListViews ProductListViews { get; }
		ProductRefundAmount ProductRefundAmount { get; }
		ProductRefunds ProductRefunds { get; }
		ProductRemovesFromCart ProductRemovesFromCart { get; }
		QuantityAddedToCart QuantityAddedToCart { get; }
		QuantityCheckedOut QuantityCheckedOut { get; }
		QuantityRefunded QuantityRefunded { get; }
		QuantityRemovedFromCart QuantityRemovedFromCart { get; }
		QueryProductQuantity QueryProductQuantity { get; }
		RefundAmount RefundAmount { get; }
		RelatedProductQuantity RelatedProductQuantity { get; }
		RevenuePerUser RevenuePerUser { get; }
		SessionsPerUser SessionsPerUser { get; }
		TotalRefunds TotalRefunds { get; }
		TransactionsPerUser TransactionsPerUser { get; }
		UserType UserType { get; }
		SessionCount SessionCount { get; }
		DaysSinceLastSession DaysSinceLastSession { get; }
		UserDefinedValue UserDefinedValue { get; }
		SessionDurationBucket SessionDurationBucket { get; }
		ReferralPath ReferralPath { get; }
		FullReferrer FullReferrer { get; }
		Campaign Campaign { get; }
		Source Source { get; }
		Medium Medium { get; }
		SourceMedium SourceMedium { get; }
		Keyword Keyword { get; }
		AdContent AdContent { get; }
		SocialNetwork SocialNetwork { get; }
		HasSocialSourceReferral HasSocialSourceReferral { get; }
		AdGroup AdGroup { get; }
		AdSlot AdSlot { get; }
		AdDistributionNetwork AdDistributionNetwork { get; }
		AdMatchType AdMatchType { get; }
		AdKeywordMatchType AdKeywordMatchType { get; }
		AdMatchedQuery AdMatchedQuery { get; }
		AdPlacementDomain AdPlacementDomain { get; }
		AdPlacementUrl AdPlacementUrl { get; }
		AdFormat AdFormat { get; }
		AdTargetingType AdTargetingType { get; }
		AdTargetingOption AdTargetingOption { get; }
		AdDisplayUrl AdDisplayUrl { get; }
		AdDestinationUrl AdDestinationUrl { get; }
		AdwordsCustomerId AdwordsCustomerId { get; }
		AdwordsCampaignId AdwordsCampaignId { get; }
		AdwordsAdGroupId AdwordsAdGroupId { get; }
		AdwordsCreativeId AdwordsCreativeId { get; }
		AdwordsCriteriaId AdwordsCriteriaId { get; }
		AdQueryWordCount AdQueryWordCount { get; }
		GoalCompletionLocation GoalCompletionLocation { get; }
		GoalPreviousStep1 GoalPreviousStep1 { get; }
		GoalPreviousStep2 GoalPreviousStep2 { get; }
		GoalPreviousStep3 GoalPreviousStep3 { get; }
		Browser Browser { get; }
		BrowserVersion BrowserVersion { get; }
		OperatingSystem OperatingSystem { get; }
		OperatingSystemVersion OperatingSystemVersion { get; }
		MobileDeviceBranding MobileDeviceBranding { get; }
		MobileDeviceModel MobileDeviceModel { get; }
		MobileInputSelector MobileInputSelector { get; }
		MobileDeviceInfo MobileDeviceInfo { get; }
		MobileDeviceMarketingName MobileDeviceMarketingName { get; }
		DeviceCategory DeviceCategory { get; }
		Continent Continent { get; }
		SubContinent SubContinent { get; }
		Country Country { get; }
		Region Region { get; }
		Metro Metro { get; }
		City City { get; }
		Latitude Latitude { get; }
		Longitude Longitude { get; }
		NetworkDomain NetworkDomain { get; }
		NetworkLocation NetworkLocation { get; }
		FlashVersion FlashVersion { get; }
		JavaEnabled JavaEnabled { get; }
		Language Language { get; }
		ScreenColors ScreenColors { get; }
		SourcePropertyDisplayName SourcePropertyDisplayName { get; }
		SourcePropertyTrackingId SourcePropertyTrackingId { get; }
		ScreenResolution ScreenResolution { get; }
		SocialActivityEndorsingUrl SocialActivityEndorsingUrl { get; }
		SocialActivityDisplayName SocialActivityDisplayName { get; }
		SocialActivityPost SocialActivityPost { get; }
		SocialActivityTimestamp SocialActivityTimestamp { get; }
		SocialActivityUserHandle SocialActivityUserHandle { get; }
		SocialActivityUserPhotoUrl SocialActivityUserPhotoUrl { get; }
		SocialActivityUserProfileUrl SocialActivityUserProfileUrl { get; }
		SocialActivityContentUrl SocialActivityContentUrl { get; }
		SocialActivityTagsSummary SocialActivityTagsSummary { get; }
		SocialActivityAction SocialActivityAction { get; }
		SocialActivityNetworkAction SocialActivityNetworkAction { get; }
		Hostname Hostname { get; }
		PagePath PagePath { get; }
		PagePathLevel1 PagePathLevel1 { get; }
		PagePathLevel2 PagePathLevel2 { get; }
		PagePathLevel3 PagePathLevel3 { get; }
		PagePathLevel4 PagePathLevel4 { get; }
		PageTitle PageTitle { get; }
		LandingPagePath LandingPagePath { get; }
		SecondPagePath SecondPagePath { get; }
		ExitPagePath ExitPagePath { get; }
		PreviousPagePath PreviousPagePath { get; }
		PageDepth PageDepth { get; }
		SearchUsed SearchUsed { get; }
		SearchKeyword SearchKeyword { get; }
		SearchKeywordRefinement SearchKeywordRefinement { get; }
		SearchCategory SearchCategory { get; }
		SearchStartPage SearchStartPage { get; }
		SearchDestinationPage SearchDestinationPage { get; }
		SearchAfterDestinationPage SearchAfterDestinationPage { get; }
		AppInstallerId AppInstallerId { get; }
		AppVersion AppVersion { get; }
		AppName AppName { get; }
		AppId AppId { get; }
		ScreenName ScreenName { get; }
		ScreenDepth ScreenDepth { get; }
		LandingScreenName LandingScreenName { get; }
		ExitScreenName ExitScreenName { get; }
		EventCategory EventCategory { get; }
		EventAction EventAction { get; }
		EventLabel EventLabel { get; }
		TransactionId TransactionId { get; }
		Affiliation Affiliation { get; }
		SessionsToTransaction SessionsToTransaction { get; }
		DaysToTransaction DaysToTransaction { get; }
		ProductSku ProductSku { get; }
		ProductName ProductName { get; }
		ProductCategory ProductCategory { get; }
		CurrencyCode CurrencyCode { get; }
		SocialInteractionNetwork SocialInteractionNetwork { get; }
		SocialInteractionAction SocialInteractionAction { get; }
		SocialInteractionNetworkAction SocialInteractionNetworkAction { get; }
		SocialInteractionTarget SocialInteractionTarget { get; }
		SocialEngagementType SocialEngagementType { get; }
		UserTimingCategory UserTimingCategory { get; }
		UserTimingLabel UserTimingLabel { get; }
		UserTimingVariable UserTimingVariable { get; }
		ExceptionDescription ExceptionDescription { get; }
		ExperimentId ExperimentId { get; }
		ExperimentVariant ExperimentVariant { get; }
		Date Date { get; }
		Year Year { get; }
		Month Month { get; }
		Week Week { get; }
		Day Day { get; }
		Hour Hour { get; }
		Minute Minute { get; }
		NthMonth NthMonth { get; }
		NthWeek NthWeek { get; }
		NthDay NthDay { get; }
		NthMinute NthMinute { get; }
		DayOfWeek DayOfWeek { get; }
		DayOfWeekName DayOfWeekName { get; }
		DateHour DateHour { get; }
		YearMonth YearMonth { get; }
		YearWeek YearWeek { get; }
		IsoWeek IsoWeek { get; }
		IsoYear IsoYear { get; }
		IsoYearIsoWeek IsoYearIsoWeek { get; }
		DcmClickAd DcmClickAd { get; }
		DcmClickAdId DcmClickAdId { get; }
		DcmClickAdType DcmClickAdType { get; }
		DcmClickAdTypeId DcmClickAdTypeId { get; }
		DcmClickAdvertiser DcmClickAdvertiser { get; }
		DcmClickAdvertiserId DcmClickAdvertiserId { get; }
		DcmClickCampaign DcmClickCampaign { get; }
		DcmClickCampaignId DcmClickCampaignId { get; }
		DcmClickCreativeId DcmClickCreativeId { get; }
		DcmClickCreative DcmClickCreative { get; }
		DcmClickRenderingId DcmClickRenderingId { get; }
		DcmClickCreativeType DcmClickCreativeType { get; }
		DcmClickCreativeTypeId DcmClickCreativeTypeId { get; }
		DcmClickCreativeVersion DcmClickCreativeVersion { get; }
		DcmClickSite DcmClickSite { get; }
		DcmClickSiteId DcmClickSiteId { get; }
		DcmClickSitePlacement DcmClickSitePlacement { get; }
		DcmClickSitePlacementId DcmClickSitePlacementId { get; }
		DcmClickSpotId DcmClickSpotId { get; }
		DcmFloodlightActivity DcmFloodlightActivity { get; }
		DcmFloodlightActivityAndGroup DcmFloodlightActivityAndGroup { get; }
		DcmFloodlightActivityGroup DcmFloodlightActivityGroup { get; }
		DcmFloodlightActivityGroupId DcmFloodlightActivityGroupId { get; }
		DcmFloodlightActivityId DcmFloodlightActivityId { get; }
		DcmFloodlightAdvertiserId DcmFloodlightAdvertiserId { get; }
		DcmFloodlightSpotId DcmFloodlightSpotId { get; }
		DcmLastEventAd DcmLastEventAd { get; }
		DcmLastEventAdId DcmLastEventAdId { get; }
		DcmLastEventAdType DcmLastEventAdType { get; }
		DcmLastEventAdTypeId DcmLastEventAdTypeId { get; }
		DcmLastEventAdvertiser DcmLastEventAdvertiser { get; }
		DcmLastEventAdvertiserId DcmLastEventAdvertiserId { get; }
		DcmLastEventAttributionType DcmLastEventAttributionType { get; }
		DcmLastEventCampaign DcmLastEventCampaign { get; }
		DcmLastEventCampaignId DcmLastEventCampaignId { get; }
		DcmLastEventCreativeId DcmLastEventCreativeId { get; }
		DcmLastEventCreative DcmLastEventCreative { get; }
		DcmLastEventRenderingId DcmLastEventRenderingId { get; }
		DcmLastEventCreativeType DcmLastEventCreativeType { get; }
		DcmLastEventCreativeTypeId DcmLastEventCreativeTypeId { get; }
		DcmLastEventCreativeVersion DcmLastEventCreativeVersion { get; }
		DcmLastEventSite DcmLastEventSite { get; }
		DcmLastEventSiteId DcmLastEventSiteId { get; }
		DcmLastEventSitePlacement DcmLastEventSitePlacement { get; }
		DcmLastEventSitePlacementId DcmLastEventSitePlacementId { get; }
		DcmLastEventSpotId DcmLastEventSpotId { get; }
		UserAgeBracket UserAgeBracket { get; }
		UserGender UserGender { get; }
		InterestOtherCategory InterestOtherCategory { get; }
		InterestAffinityCategory InterestAffinityCategory { get; }
		InterestInMarketCategory InterestInMarketCategory { get; }
		BrowserSize BrowserSize { get; }
		CampaignCode CampaignCode { get; }
		ChannelGrouping ChannelGrouping { get; }
		CheckoutOptions CheckoutOptions { get; }
		CityId CityId { get; }
		CorrelationModelId CorrelationModelId { get; }
		CountryIsoCode CountryIsoCode { get; }
		DataSource DataSource { get; }
		InternalPromotionCreative InternalPromotionCreative { get; }
		InternalPromotionId InternalPromotionId { get; }
		InternalPromotionName InternalPromotionName { get; }
		InternalPromotionPosition InternalPromotionPosition { get; }
		IsTrueViewVideoAd IsTrueViewVideoAd { get; }
		NthHour NthHour { get; }
		OrderCouponCode OrderCouponCode { get; }
		ProductBrand ProductBrand { get; }
		ProductCategoryHierarchy ProductCategoryHierarchy { get; }
		ProductCouponCode ProductCouponCode { get; }
		ProductListName ProductListName { get; }
		ProductListPosition ProductListPosition { get; }
		ProductVariant ProductVariant { get; }
		QueryProductId QueryProductId { get; }
		QueryProductName QueryProductName { get; }
		QueryProductVariation QueryProductVariation { get; }
		RegionId RegionId { get; }
		RegionIsoCode RegionIsoCode { get; }
		RelatedProductId RelatedProductId { get; }
		RelatedProductName RelatedProductName { get; }
		RelatedProductVariation RelatedProductVariation { get; }
		ShoppingStage ShoppingStage { get; }
		SubContinentCode SubContinentCode { get; }
	}
}

