using LinqAn.Google.Metrics;
using LinqAn.Google.Dimensions;

namespace LinqAn.Google.Records
{
	public class QueryableRecord : IQueryableRecord
	{
		public uint ViewId { get; set; }
		public System.DateTime RecordDate { get; set; }
		public Users Users { get; set; }
		public NewUsers NewUsers { get; set; }
		public OnedayUsers OnedayUsers { get; set; }
		public SevendayUsers SevendayUsers { get; set; }
		public FourteendayUsers FourteendayUsers { get; set; }
		public ThirtydayUsers ThirtydayUsers { get; set; }
		public Sessions Sessions { get; set; }
		public Bounces Bounces { get; set; }
		public SessionDuration SessionDuration { get; set; }
		public OrganicSearches OrganicSearches { get; set; }
		public Impressions Impressions { get; set; }
		public AdClicks AdClicks { get; set; }
		public AdCost AdCost { get; set; }
		public GoalStartsAll GoalStartsAll { get; set; }
		public GoalCompletionsAll GoalCompletionsAll { get; set; }
		public GoalValueAll GoalValueAll { get; set; }
		public SocialActivities SocialActivities { get; set; }
		public PageValue PageValue { get; set; }
		public Entrances Entrances { get; set; }
		public Pageviews Pageviews { get; set; }
		public UniquePageviews UniquePageviews { get; set; }
		public TimeOnPage TimeOnPage { get; set; }
		public Exits Exits { get; set; }
		public SearchResultViews SearchResultViews { get; set; }
		public SearchUniques SearchUniques { get; set; }
		public SearchSessions SearchSessions { get; set; }
		public SearchDepth SearchDepth { get; set; }
		public SearchRefinements SearchRefinements { get; set; }
		public SearchDuration SearchDuration { get; set; }
		public SearchExits SearchExits { get; set; }
		public PageLoadTime PageLoadTime { get; set; }
		public PageLoadSample PageLoadSample { get; set; }
		public DomainLookupTime DomainLookupTime { get; set; }
		public PageDownloadTime PageDownloadTime { get; set; }
		public RedirectionTime RedirectionTime { get; set; }
		public ServerConnectionTime ServerConnectionTime { get; set; }
		public ServerResponseTime ServerResponseTime { get; set; }
		public SpeedMetricsSample SpeedMetricsSample { get; set; }
		public DomInteractiveTime DomInteractiveTime { get; set; }
		public DomContentLoadedTime DomContentLoadedTime { get; set; }
		public DomLatencyMetricsSample DomLatencyMetricsSample { get; set; }
		public Screenviews Screenviews { get; set; }
		public UniqueScreenviews UniqueScreenviews { get; set; }
		public TimeOnScreen TimeOnScreen { get; set; }
		public AvgScreenviewDuration AvgScreenviewDuration { get; set; }
		public TotalEvents TotalEvents { get; set; }
		public UniqueEvents UniqueEvents { get; set; }
		public EventValue EventValue { get; set; }
		public SessionsWithEvent SessionsWithEvent { get; set; }
		public Transactions Transactions { get; set; }
		public TransactionRevenue TransactionRevenue { get; set; }
		public TransactionShipping TransactionShipping { get; set; }
		public TransactionTax TransactionTax { get; set; }
		public ItemQuantity ItemQuantity { get; set; }
		public UniquePurchases UniquePurchases { get; set; }
		public ItemRevenue ItemRevenue { get; set; }
		public LocalTransactionRevenue LocalTransactionRevenue { get; set; }
		public LocalTransactionShipping LocalTransactionShipping { get; set; }
		public LocalTransactionTax LocalTransactionTax { get; set; }
		public LocalItemRevenue LocalItemRevenue { get; set; }
		public SocialInteractions SocialInteractions { get; set; }
		public UniqueSocialInteractions UniqueSocialInteractions { get; set; }
		public UserTimingValue UserTimingValue { get; set; }
		public UserTimingSample UserTimingSample { get; set; }
		public Exceptions Exceptions { get; set; }
		public FatalExceptions FatalExceptions { get; set; }
		public DcmFloodlightQuantity DcmFloodlightQuantity { get; set; }
		public DcmFloodlightRevenue DcmFloodlightRevenue { get; set; }
		public AdsenseRevenue AdsenseRevenue { get; set; }
		public AdsenseAdUnitsViewed AdsenseAdUnitsViewed { get; set; }
		public AdsenseAdsViewed AdsenseAdsViewed { get; set; }
		public AdsenseAdsClicks AdsenseAdsClicks { get; set; }
		public AdsensePageImpressions AdsensePageImpressions { get; set; }
		public AdsenseExits AdsenseExits { get; set; }
		public AdsenseViewableImpressionPercent AdsenseViewableImpressionPercent { get; set; }
		public AdsenseCoverage AdsenseCoverage { get; set; }
		public AdxImpressions AdxImpressions { get; set; }
		public AdxCoverage AdxCoverage { get; set; }
		public AdxMonetizedPageviews AdxMonetizedPageviews { get; set; }
		public AdxImpressionsPerSession AdxImpressionsPerSession { get; set; }
		public AdxViewableImpressionsPercent AdxViewableImpressionsPercent { get; set; }
		public AdxClicks AdxClicks { get; set; }
		public AdxCTR AdxCTR { get; set; }
		public AdxRevenue AdxRevenue { get; set; }
		public AdxRevenuePer1000Sessions AdxRevenuePer1000Sessions { get; set; }
		public AdxECPM AdxECPM { get; set; }
		public BuyToDetailRate BuyToDetailRate { get; set; }
		public CartToDetailRate CartToDetailRate { get; set; }
		public CorrelationScore CorrelationScore { get; set; }
		public DcmCPC DcmCPC { get; set; }
		public DcmCTR DcmCTR { get; set; }
		public DcmClicks DcmClicks { get; set; }
		public DcmCost DcmCost { get; set; }
		public DcmImpressions DcmImpressions { get; set; }
		public DcmROAS DcmROAS { get; set; }
		public DcmRPC DcmRPC { get; set; }
		public Hits Hits { get; set; }
		public InternalPromotionClicks InternalPromotionClicks { get; set; }
		public InternalPromotionViews InternalPromotionViews { get; set; }
		public LocalProductRefundAmount LocalProductRefundAmount { get; set; }
		public LocalRefundAmount LocalRefundAmount { get; set; }
		public ProductAddsToCart ProductAddsToCart { get; set; }
		public ProductCheckouts ProductCheckouts { get; set; }
		public ProductDetailViews ProductDetailViews { get; set; }
		public ProductListClicks ProductListClicks { get; set; }
		public ProductListViews ProductListViews { get; set; }
		public ProductRefundAmount ProductRefundAmount { get; set; }
		public ProductRefunds ProductRefunds { get; set; }
		public ProductRemovesFromCart ProductRemovesFromCart { get; set; }
		public QuantityAddedToCart QuantityAddedToCart { get; set; }
		public QuantityCheckedOut QuantityCheckedOut { get; set; }
		public QuantityRefunded QuantityRefunded { get; set; }
		public QuantityRemovedFromCart QuantityRemovedFromCart { get; set; }
		public QueryProductQuantity QueryProductQuantity { get; set; }
		public RefundAmount RefundAmount { get; set; }
		public RelatedProductQuantity RelatedProductQuantity { get; set; }
		public RevenuePerUser RevenuePerUser { get; set; }
		public SessionsPerUser SessionsPerUser { get; set; }
		public TotalRefunds TotalRefunds { get; set; }
		public TransactionsPerUser TransactionsPerUser { get; set; }
		public UserType UserType { get; set; }
		public SessionCount SessionCount { get; set; }
		public DaysSinceLastSession DaysSinceLastSession { get; set; }
		public UserDefinedValue UserDefinedValue { get; set; }
		public SessionDurationBucket SessionDurationBucket { get; set; }
		public ReferralPath ReferralPath { get; set; }
		public FullReferrer FullReferrer { get; set; }
		public Campaign Campaign { get; set; }
		public Source Source { get; set; }
		public Medium Medium { get; set; }
		public SourceMedium SourceMedium { get; set; }
		public Keyword Keyword { get; set; }
		public AdContent AdContent { get; set; }
		public SocialNetwork SocialNetwork { get; set; }
		public HasSocialSourceReferral HasSocialSourceReferral { get; set; }
		public AdGroup AdGroup { get; set; }
		public AdSlot AdSlot { get; set; }
		public AdDistributionNetwork AdDistributionNetwork { get; set; }
		public AdMatchType AdMatchType { get; set; }
		public AdKeywordMatchType AdKeywordMatchType { get; set; }
		public AdMatchedQuery AdMatchedQuery { get; set; }
		public AdPlacementDomain AdPlacementDomain { get; set; }
		public AdPlacementUrl AdPlacementUrl { get; set; }
		public AdFormat AdFormat { get; set; }
		public AdTargetingType AdTargetingType { get; set; }
		public AdTargetingOption AdTargetingOption { get; set; }
		public AdDisplayUrl AdDisplayUrl { get; set; }
		public AdDestinationUrl AdDestinationUrl { get; set; }
		public AdwordsCustomerId AdwordsCustomerId { get; set; }
		public AdwordsCampaignId AdwordsCampaignId { get; set; }
		public AdwordsAdGroupId AdwordsAdGroupId { get; set; }
		public AdwordsCreativeId AdwordsCreativeId { get; set; }
		public AdwordsCriteriaId AdwordsCriteriaId { get; set; }
		public AdQueryWordCount AdQueryWordCount { get; set; }
		public GoalCompletionLocation GoalCompletionLocation { get; set; }
		public GoalPreviousStep1 GoalPreviousStep1 { get; set; }
		public GoalPreviousStep2 GoalPreviousStep2 { get; set; }
		public GoalPreviousStep3 GoalPreviousStep3 { get; set; }
		public Browser Browser { get; set; }
		public BrowserVersion BrowserVersion { get; set; }
		public OperatingSystem OperatingSystem { get; set; }
		public OperatingSystemVersion OperatingSystemVersion { get; set; }
		public MobileDeviceBranding MobileDeviceBranding { get; set; }
		public MobileDeviceModel MobileDeviceModel { get; set; }
		public MobileInputSelector MobileInputSelector { get; set; }
		public MobileDeviceInfo MobileDeviceInfo { get; set; }
		public MobileDeviceMarketingName MobileDeviceMarketingName { get; set; }
		public DeviceCategory DeviceCategory { get; set; }
		public Continent Continent { get; set; }
		public SubContinent SubContinent { get; set; }
		public Country Country { get; set; }
		public Region Region { get; set; }
		public Metro Metro { get; set; }
		public City City { get; set; }
		public Latitude Latitude { get; set; }
		public Longitude Longitude { get; set; }
		public NetworkDomain NetworkDomain { get; set; }
		public NetworkLocation NetworkLocation { get; set; }
		public FlashVersion FlashVersion { get; set; }
		public JavaEnabled JavaEnabled { get; set; }
		public Language Language { get; set; }
		public ScreenColors ScreenColors { get; set; }
		public SourcePropertyDisplayName SourcePropertyDisplayName { get; set; }
		public SourcePropertyTrackingId SourcePropertyTrackingId { get; set; }
		public ScreenResolution ScreenResolution { get; set; }
		public SocialActivityEndorsingUrl SocialActivityEndorsingUrl { get; set; }
		public SocialActivityDisplayName SocialActivityDisplayName { get; set; }
		public SocialActivityPost SocialActivityPost { get; set; }
		public SocialActivityTimestamp SocialActivityTimestamp { get; set; }
		public SocialActivityUserHandle SocialActivityUserHandle { get; set; }
		public SocialActivityUserPhotoUrl SocialActivityUserPhotoUrl { get; set; }
		public SocialActivityUserProfileUrl SocialActivityUserProfileUrl { get; set; }
		public SocialActivityContentUrl SocialActivityContentUrl { get; set; }
		public SocialActivityTagsSummary SocialActivityTagsSummary { get; set; }
		public SocialActivityAction SocialActivityAction { get; set; }
		public SocialActivityNetworkAction SocialActivityNetworkAction { get; set; }
		public Hostname Hostname { get; set; }
		public PagePath PagePath { get; set; }
		public PagePathLevel1 PagePathLevel1 { get; set; }
		public PagePathLevel2 PagePathLevel2 { get; set; }
		public PagePathLevel3 PagePathLevel3 { get; set; }
		public PagePathLevel4 PagePathLevel4 { get; set; }
		public PageTitle PageTitle { get; set; }
		public LandingPagePath LandingPagePath { get; set; }
		public SecondPagePath SecondPagePath { get; set; }
		public ExitPagePath ExitPagePath { get; set; }
		public PreviousPagePath PreviousPagePath { get; set; }
		public PageDepth PageDepth { get; set; }
		public SearchUsed SearchUsed { get; set; }
		public SearchKeyword SearchKeyword { get; set; }
		public SearchKeywordRefinement SearchKeywordRefinement { get; set; }
		public SearchCategory SearchCategory { get; set; }
		public SearchStartPage SearchStartPage { get; set; }
		public SearchDestinationPage SearchDestinationPage { get; set; }
		public SearchAfterDestinationPage SearchAfterDestinationPage { get; set; }
		public AppInstallerId AppInstallerId { get; set; }
		public AppVersion AppVersion { get; set; }
		public AppName AppName { get; set; }
		public AppId AppId { get; set; }
		public ScreenName ScreenName { get; set; }
		public ScreenDepth ScreenDepth { get; set; }
		public LandingScreenName LandingScreenName { get; set; }
		public ExitScreenName ExitScreenName { get; set; }
		public EventCategory EventCategory { get; set; }
		public EventAction EventAction { get; set; }
		public EventLabel EventLabel { get; set; }
		public TransactionId TransactionId { get; set; }
		public Affiliation Affiliation { get; set; }
		public SessionsToTransaction SessionsToTransaction { get; set; }
		public DaysToTransaction DaysToTransaction { get; set; }
		public ProductSku ProductSku { get; set; }
		public ProductName ProductName { get; set; }
		public ProductCategory ProductCategory { get; set; }
		public CurrencyCode CurrencyCode { get; set; }
		public SocialInteractionNetwork SocialInteractionNetwork { get; set; }
		public SocialInteractionAction SocialInteractionAction { get; set; }
		public SocialInteractionNetworkAction SocialInteractionNetworkAction { get; set; }
		public SocialInteractionTarget SocialInteractionTarget { get; set; }
		public SocialEngagementType SocialEngagementType { get; set; }
		public UserTimingCategory UserTimingCategory { get; set; }
		public UserTimingLabel UserTimingLabel { get; set; }
		public UserTimingVariable UserTimingVariable { get; set; }
		public ExceptionDescription ExceptionDescription { get; set; }
		public ExperimentId ExperimentId { get; set; }
		public ExperimentVariant ExperimentVariant { get; set; }
		public Date Date { get; set; }
		public Year Year { get; set; }
		public Month Month { get; set; }
		public Week Week { get; set; }
		public Day Day { get; set; }
		public Hour Hour { get; set; }
		public Minute Minute { get; set; }
		public NthMonth NthMonth { get; set; }
		public NthWeek NthWeek { get; set; }
		public NthDay NthDay { get; set; }
		public NthMinute NthMinute { get; set; }
		public DayOfWeek DayOfWeek { get; set; }
		public DayOfWeekName DayOfWeekName { get; set; }
		public DateHour DateHour { get; set; }
		public YearMonth YearMonth { get; set; }
		public YearWeek YearWeek { get; set; }
		public IsoWeek IsoWeek { get; set; }
		public IsoYear IsoYear { get; set; }
		public IsoYearIsoWeek IsoYearIsoWeek { get; set; }
		public DcmClickAd DcmClickAd { get; set; }
		public DcmClickAdId DcmClickAdId { get; set; }
		public DcmClickAdType DcmClickAdType { get; set; }
		public DcmClickAdTypeId DcmClickAdTypeId { get; set; }
		public DcmClickAdvertiser DcmClickAdvertiser { get; set; }
		public DcmClickAdvertiserId DcmClickAdvertiserId { get; set; }
		public DcmClickCampaign DcmClickCampaign { get; set; }
		public DcmClickCampaignId DcmClickCampaignId { get; set; }
		public DcmClickCreativeId DcmClickCreativeId { get; set; }
		public DcmClickCreative DcmClickCreative { get; set; }
		public DcmClickRenderingId DcmClickRenderingId { get; set; }
		public DcmClickCreativeType DcmClickCreativeType { get; set; }
		public DcmClickCreativeTypeId DcmClickCreativeTypeId { get; set; }
		public DcmClickCreativeVersion DcmClickCreativeVersion { get; set; }
		public DcmClickSite DcmClickSite { get; set; }
		public DcmClickSiteId DcmClickSiteId { get; set; }
		public DcmClickSitePlacement DcmClickSitePlacement { get; set; }
		public DcmClickSitePlacementId DcmClickSitePlacementId { get; set; }
		public DcmClickSpotId DcmClickSpotId { get; set; }
		public DcmFloodlightActivity DcmFloodlightActivity { get; set; }
		public DcmFloodlightActivityAndGroup DcmFloodlightActivityAndGroup { get; set; }
		public DcmFloodlightActivityGroup DcmFloodlightActivityGroup { get; set; }
		public DcmFloodlightActivityGroupId DcmFloodlightActivityGroupId { get; set; }
		public DcmFloodlightActivityId DcmFloodlightActivityId { get; set; }
		public DcmFloodlightAdvertiserId DcmFloodlightAdvertiserId { get; set; }
		public DcmFloodlightSpotId DcmFloodlightSpotId { get; set; }
		public DcmLastEventAd DcmLastEventAd { get; set; }
		public DcmLastEventAdId DcmLastEventAdId { get; set; }
		public DcmLastEventAdType DcmLastEventAdType { get; set; }
		public DcmLastEventAdTypeId DcmLastEventAdTypeId { get; set; }
		public DcmLastEventAdvertiser DcmLastEventAdvertiser { get; set; }
		public DcmLastEventAdvertiserId DcmLastEventAdvertiserId { get; set; }
		public DcmLastEventAttributionType DcmLastEventAttributionType { get; set; }
		public DcmLastEventCampaign DcmLastEventCampaign { get; set; }
		public DcmLastEventCampaignId DcmLastEventCampaignId { get; set; }
		public DcmLastEventCreativeId DcmLastEventCreativeId { get; set; }
		public DcmLastEventCreative DcmLastEventCreative { get; set; }
		public DcmLastEventRenderingId DcmLastEventRenderingId { get; set; }
		public DcmLastEventCreativeType DcmLastEventCreativeType { get; set; }
		public DcmLastEventCreativeTypeId DcmLastEventCreativeTypeId { get; set; }
		public DcmLastEventCreativeVersion DcmLastEventCreativeVersion { get; set; }
		public DcmLastEventSite DcmLastEventSite { get; set; }
		public DcmLastEventSiteId DcmLastEventSiteId { get; set; }
		public DcmLastEventSitePlacement DcmLastEventSitePlacement { get; set; }
		public DcmLastEventSitePlacementId DcmLastEventSitePlacementId { get; set; }
		public DcmLastEventSpotId DcmLastEventSpotId { get; set; }
		public UserAgeBracket UserAgeBracket { get; set; }
		public UserGender UserGender { get; set; }
		public InterestOtherCategory InterestOtherCategory { get; set; }
		public InterestAffinityCategory InterestAffinityCategory { get; set; }
		public InterestInMarketCategory InterestInMarketCategory { get; set; }
		public BrowserSize BrowserSize { get; set; }
		public CampaignCode CampaignCode { get; set; }
		public ChannelGrouping ChannelGrouping { get; set; }
		public CheckoutOptions CheckoutOptions { get; set; }
		public CityId CityId { get; set; }
		public CorrelationModelId CorrelationModelId { get; set; }
		public CountryIsoCode CountryIsoCode { get; set; }
		public DataSource DataSource { get; set; }
		public InternalPromotionCreative InternalPromotionCreative { get; set; }
		public InternalPromotionId InternalPromotionId { get; set; }
		public InternalPromotionName InternalPromotionName { get; set; }
		public InternalPromotionPosition InternalPromotionPosition { get; set; }
		public IsTrueViewVideoAd IsTrueViewVideoAd { get; set; }
		public NthHour NthHour { get; set; }
		public OrderCouponCode OrderCouponCode { get; set; }
		public ProductBrand ProductBrand { get; set; }
		public ProductCategoryHierarchy ProductCategoryHierarchy { get; set; }
		public ProductCouponCode ProductCouponCode { get; set; }
		public ProductListName ProductListName { get; set; }
		public ProductListPosition ProductListPosition { get; set; }
		public ProductVariant ProductVariant { get; set; }
		public QueryProductId QueryProductId { get; set; }
		public QueryProductName QueryProductName { get; set; }
		public QueryProductVariation QueryProductVariation { get; set; }
		public RegionId RegionId { get; set; }
		public RegionIsoCode RegionIsoCode { get; set; }
		public RelatedProductId RelatedProductId { get; set; }
		public RelatedProductName RelatedProductName { get; set; }
		public RelatedProductVariation RelatedProductVariation { get; set; }
		public ShoppingStage ShoppingStage { get; set; }
		public SubContinentCode SubContinentCode { get; set; }
	}
}

